/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package allmem;

import AllBooks.allbooks;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import mainpage.mainPage;

/**
 *
 * @author PC
 */
public class allmem extends javax.swing.JFrame {

    /**
     * Creates new form allmem
     */
    public allmem() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("ic.png")).getImage();
        this.setIconImage(icon);
    }
    EDITMODE1 edit = new EDITMODE1();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(189, 195, 199));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FULL NAME ", "AGE", "EMAIL", "PHONE NUMBRE ", "BIRTH DAY "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 850, 270));

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 40));

        jLabel2.setText(" SEARCHE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, -1));

        jButton1.setBackground(new java.awt.Color(0, 98, 227));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOAD");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 50));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        jButton2.setBackground(new java.awt.Color(227, 42, 23));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DELETE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 220, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Total Members :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, 20));

        total.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 40, 20));

        jButton3.setBackground(new java.awt.Color(0, 98, 227));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EDIT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/allmem/all MEMBERS.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        mainPage gotomain = new mainPage();
        gotomain.show();
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked
public int howmem(){
    int howmanyM = jTable1.getRowCount();
    return howmanyM;
}
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //set new table
        
        int s = 0;
        try {
            FileReader frr = new FileReader("members.txt");
            BufferedReader brr = new BufferedReader(frr);
            
            
            DefaultTableModel model2 = (DefaultTableModel)jTable1.getModel();
            //***************************************************************
            while(model2.getRowCount()>0){
                for(int i=0;i<model2.getRowCount();i++){
                    model2.removeRow(i);
                }
            }
            
            
            Object[] lines2 =brr.lines().toArray();
            
            for(int i =0;i<lines2.length;i++){
              //  s = i;
                
                String[] row = lines2[i].toString().split(";;");
                model2.addRow(row);
                s+=1;
            }
            total.setText(" "+s);
            //s=model2.getRowCount();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(allbooks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
        DefaultTableModel table3 = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(table3);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search.getText().trim()));
    }//GEN-LAST:event_searchKeyPressed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table3 = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(table3);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search.getText().trim()));
    }//GEN-LAST:event_searchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRowCount()== 1 ){
             int yes = JOptionPane.showConfirmDialog(this, "Are You Sure !?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
             if (yes == JOptionPane.YES_OPTION){
                 
             
             DefaultTableModel tlb = (DefaultTableModel) jTable1.getModel();
             tlb.removeRow(jTable1.getSelectedRow());
             
             
             //save the new jdwl
             try {
            FileWriter fw = new FileWriter("members.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0 ; i<jTable1.getRowCount();i++){
                for(int j=0;j<jTable1.getColumnCount();j++){
                    
                    bw.write(jTable1.getValueAt(i, j).toString()+ ";;");
                   
                }
                bw.newLine();
                
            }
            bw.newLine();
            bw.close();
            fw.close();
            
            
        } catch (IOException ex) {
            Logger.getLogger(allbooks.class.getName()).log(Level.SEVERE, null, ex);
        }
             
             
             
              }
        }else{
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table Is Empty...");
            }else {
                JOptionPane.showMessageDialog(this, "Please Select 1 Row To Delete...");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRowCount()==1){
            int index = jTable1.getSelectedRow();
            TableModel tlb = jTable1.getModel();
            // get info
            String id = jTable1.getValueAt(index, 0).toString();
            String name = jTable1.getValueAt(index, 1).toString();
            String age = jTable1.getValueAt(index, 2).toString();
            String email = jTable1.getValueAt(index, 3).toString();
            String num = jTable1.getValueAt(index, 4).toString();
            String dat = jTable1.getValueAt(index, 5).toString();

            edit.setVisible(true);
            edit.pack();
            edit.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            // set data
            edit.idtxt.setText(id);
            edit.nametxt.setText(name);
            edit.agetxt.setText(age);
            edit.emailtxt.setText(email);
            edit.numtxt.setText(num);
            //edit.birth.setDateFormatString(dat);

            DefaultTableModel tlb1;
            tlb1 = (DefaultTableModel) jTable1.getModel();
            tlb1.removeRow(jTable1.getSelectedRow());
            try {
                FileWriter fw = new FileWriter("members.txt");
                BufferedWriter bw = new BufferedWriter(fw);

                for(int i=0 ; i<jTable1.getRowCount();i++){
                    for(int j=0;j<jTable1.getColumnCount();j++){

                        bw.write(jTable1.getValueAt(i, j).toString()+ ";;");

                    }
                    bw.newLine();

                }

                bw.close();
                fw.close();

            } catch (IOException ex) {
                Logger.getLogger(allbooks.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allmem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allmem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allmem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allmem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allmem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField search;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
    public static void addrow(Object[] data){
      
       DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
       table.addRow(data);
       try {
            FileWriter fw = new FileWriter("members.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0 ; i<jTable1.getRowCount();i++){
                for(int j=0;j<jTable1.getColumnCount();j++){
                    
                    bw.write(jTable1.getValueAt(i, j).toString()+ ";;");
                   
                }
                bw.newLine();
                
            }
            
            bw.close();
            fw.close();
            
            
        } catch (IOException ex) {
            Logger.getLogger(allbooks.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }



}
